name: Teste de Carga

on:
  workflow_call:

jobs:
  loadtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configurando Credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - run: git clone https://github.com/jnadyr/Infra_CI.git # Clona o Terraform para criar e destruir a infra

    - name: HashiCorp - Setup Terraform # Instala o Terraform no runner
      uses: hashicorp/setup-terraform@v2.0.3

    - name: List files for debugging # passo de debug. Ele entendeu o https://github.com/jnadyr/Infra_CI.git
      run: ls -R

    - run: terraform -chdir=Infra_/CI/env/Homolog init #inicia o Terraform
    
    - run: terraform -chdir=Infra_CI/env/Homolog destroy -auto-approve # remove qq infra que for igual e que, por acaso, tenha ficado ativa. Feito antes do apply!

    - run: terraform -chdir=Infra_CI/env/Homolog apply -auto-approve  # aplica o Terraform 

    - run: echo "$(terraform -chdir=Infra_CI/env/Homolog output -raw IP_alb)"     # Executa o parêntesis e joga a saída para o terminal # No comando acima, volta o IP ou URL do alb (app load balancer)
      id: URL
             
    - name: Setup Python  # Instala o Python pq o Locust é um app Python
      uses: actions/setup-python@v6.1.0
      with:
        python-version: "3.10"
        allow-prereleases: false

    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          locust

    - run: |
       echo "from locust import HttpUser, TaskSet, task, between" >> locustfile.py
       echo "" >> locustfile.py
       echo "class UserTasks(TaskSet):" >> locustfile.py
       echo "	@task(1)" >> locustfile.py
       echo "	def index(self):" >> locustfile.py
       echo "		self.client.get("/Aurea")" >> locustfile.py
       echo "" >> locustfile.py
       echo "class WebsiteUser(HttpUser):" >> locustfile.py
       echo "	tasks = [UserTasks]" >> locustfile.py
       echo "	wait_time = between(1, 5)" >> locustfile.py
       cat locustfile.py

    - name: Roda o teste de carga
      run: sleep 60s ; locust -f locustfile.py --headless -u 10 -r 5 --run-time 60s -H http://${{ steps.URL.outputs.stdout }}
      
    - run: terraform -chdir=Infra/CI/env/Homolog destroy -auto-approve # remove qq infra que for igual e que está ativa agora!
    
